# Generated by Django 5.1.3 on 2024-11-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('GBP', 'GBP'), ('BYN', 'BYN')], default='BYN', max_length=3),
        ),
    ]
