# Generated by Django 5.1.3 on 2024-11-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COMPANY', 'Компания'), ('APPLICANT', 'Соискатель')], default='APPLICANT', max_length=20),
        ),
    ]
